const AreasList = [
  {value:'Análise de Dados e Experiência do Cliente',label:'Análise de Dados e Experiência do Cliente'},
  {value:'Analise de risco',label:'Analise de risco'},
  {value:'Análise Financeira',label:'Análise Financeira'},
  {value:'Análise química',label:'Análise química'},
  {value:'Área Comercial',label:'Área Comercial'},
  {value:'Área Comercial em Seguros',label:'Área Comercial em Seguros'},
  {value:'Área Comercial Vendas',label:'Área Comercial Vendas'},
  {value:'Área digital dentro de marketing',label:'Área digital dentro de marketing'},
  {value:'Área Social',label:'Área Social'},
  {value:'Arquitetura',label:'Arquitetura'},
  {value:'Arquitetura de Sistemas',label:'Arquitetura de Sistemas'},
  {value:'Arte Terapia',label:'Arte Terapia'},
  {value:'Artes',label:'Artes'},
  {value:'Artistica',label:'Artistica'},
  {value:'Atendimento ao Cliente',label:'Atendimento ao Cliente'},
  {value:'Atendimento ao Consumidor',label:'Atendimento ao Consumidor'},
  {value:'Auditoria',label:'Auditoria'},
  {value:'Auditoria / Contabilidade',label:'Auditoria / Contabilidade'},
  {value:'Auditoria e Contabilidade',label:'Auditoria e Contabilidade'},
  {value:'Auditoria Interna',label:'Auditoria Interna'},
  {value:'Auditoria Interna de Segurança da Informação / TI',label:'Auditoria Interna de Segurança da Informação / TI'},
  {value:'Auditoria setor Financeiro',label:'Auditoria setor Financeiro'},
  {value:'Banco',label:'Banco'},
  {value:'Biologia',label:'Biologia'},
  {value:'Biomedicina',label:'Biomedicina'},
  {value:'Branding',label:'Branding'},
  {value:'Cadeia de Suprimentos',label:'Cadeia de Suprimentos'},
  {value:'Cadeia de Suprimentos (Supply Chain)',label:'Cadeia de Suprimentos (Supply Chain)'},
  {value:'Carreira Militar',label:'Carreira Militar'},
  {value:'Ciências Sociais Aplicadas: Design',label:'Ciências Sociais Aplicadas: Design'},
  {value:'Cloud Computing',label:'Cloud Computing'},
  {value:'Coach de Carreira',label:'Coach de Carreira'},
  {value:'Coaching e Treinamentos',label:'Coaching e Treinamentos'},
  {value:'Comercial',label:'Comercial'},
  {value:'Comercial/Marketing',label:'Comercial/Marketing'},
  {value:'Comércio',label:'Comércio'},
  {value:'Compliance',label:'Compliance'},
  {value:'Compras',label:'Compras'},
  {value:'Compras / Suprimentos',label:'Compras / Suprimentos'},
  {value:'Compras/ Gestão',label:'Compras/ Gestão'},
  {value:'Comunicação',label:'Comunicação'},
  {value:'Consultoria',label:'Consultoria'},
  {value:'Consultoria em Gestão de Negócios e Mercado',label:'Consultoria em Gestão de Negócios e Mercado'},
  {value:'Criatividade',label:'Criatividade'},
  {value:'CRM',label:'CRM'},
  {value:'Customer Experience',label:'Customer Experience'},
  {value:'customer experience e design estratégico',label:'customer experience e design estratégico'},
  {value:'Customer Success',label:'Customer Success'},
  {value:'Dados e Analytics',label:'Dados e Analytics'},
  {value:'Data & Analytics',label:'Data & Analytics'},
  {value:'Data Analytics',label:'Data Analytics'},
  {value:'Data Science',label:'Data Science'},
  {value:'Desenvolvimento Comercial',label:'Desenvolvimento Comercial'},
  {value:'Desenvolvimento Comunitário.',label:'Desenvolvimento Comunitário.'},
  {value:'Desenvolvimento de Carreira',label:'Desenvolvimento de Carreira'},
  {value:'Desenvolvimento de negócios - tecnologia',label:'Desenvolvimento de negócios - tecnologia'},
  {value:'Desenvolvimento de sistemas focado na qualidade de software',label:'Desenvolvimento de sistemas focado na qualidade de software'},
  {value:'Desenvolvimento de Software',label:'Desenvolvimento de Software'},
  {value:'Desenvolvimento de Websites',label:'Desenvolvimento de Websites'},
  {value:'Design de Serviços',label:'Design de Serviços'},
  {value:'Direito',label:'Direito'},
  {value:'Diretora de Intercâmbios Voluntários na Aiesec Brasil',label:'Diretora de Intercâmbios Voluntários na Aiesec Brasil'},
  {value:'e-commerce',label:'e-commerce'},
  {value:'Educaçao',label:'Educaçao'},
  {value:'Educação',label:'Educação'},
  {value:'Educação ambiental',label:'Educação ambiental'},
  {value:'Educação e Arte',label:'Educação e Arte'},
  {value:'Educação e desenvolvimento pessoal',label:'Educação e desenvolvimento pessoal'},
  {value:'Educação e Gestão de Pessoas',label:'Educação e Gestão de Pessoas'},
  {value:'Educação e pesquisa',label:'Educação e pesquisa'},
  {value:'Educação Não-Formal',label:'Educação Não-Formal'},
  {value:'Educação; criação e execução de cenário para industria do audiovisual',label:'Educação; criação e execução de cenário para industria do audiovisual'},
  {value:'Educação/Capoeira',label:'Educação/Capoeira'},
  {value:'Eletrodomesticos - linha branca',label:'Eletrodomesticos - linha branca'},
  {value:'Empreendedorismo',label:'Empreendedorismo'},
  {value:'Empreendedorismo Social',label:'Empreendedorismo Social'},
  {value:'Energia renovável',label:'Energia renovável'},
  {value:'Energias Renováveis',label:'Energias Renováveis'},
  {value:'Engenharia',label:'Engenharia'},
  {value:'Engenharia de Alimentos',label:'Engenharia de Alimentos'},
  {value:'Escrita',label:'Escrita'},
  {value:'Estrategia',label:'Estrategia'},
  {value:'Estratégia de Produto - Indústria Farmacêutica',label:'Estratégia de Produto - Indústria Farmacêutica'},
  {value:'Ética e Integridade Científica',label:'Ética e Integridade Científica'},
  {value:'Eventos de negócios em saúde',label:'Eventos de negócios em saúde'},
  {value:'Experiência do Cliente',label:'Experiência do Cliente'},
  {value:'Experiencia do cliente no segmento de Entretenimento',label:'Experiencia do cliente no segmento de Entretenimento'},
  {value:'Filosofia',label:'Filosofia'},
  {value:'Finanças',label:'Finanças'},
  {value:'Física',label:'Física'},
  {value:'Fotografia',label:'Fotografia'},
  {value:'Geografia',label:'Geografia'},
  {value:'Gerenciamento',label:'Gerenciamento'},
  {value:'Gerenciamento de Produtos',label:'Gerenciamento de Produtos'},
  {value:'Gestão Administrativa',label:'Gestão Administrativa'},
  {value:'Gestão Ágil',label:'Gestão Ágil'},
  {value:'Gestão da Cadeia de Suprimentos',label:'Gestão da Cadeia de Suprimentos'},
  {value:'Gestão de Dados e Estratégia',label:'Gestão de Dados e Estratégia'},
  {value:'Gestão de Negócios',label:'Gestão de Negócios'},
  {value:'Gestão de pessoas',label:'Gestão de pessoas'},
  {value:'Gestão de pessoas e metas',label:'Gestão de pessoas e metas'},
  {value:'Gestão de Processos',label:'Gestão de Processos'},
  {value:'Gestão de produtos',label:'Gestão de produtos'},
  {value:'Gestão de Produtos Digitais',label:'Gestão de Produtos Digitais'},
  {value:'Gestão de Produtos.',label:'Gestão de Produtos.'},
  {value:'Gestão de Projetos',label:'Gestão de Projetos'},
  {value:'Gestão de Riscos e Prevenção de Perdas',label:'Gestão de Riscos e Prevenção de Perdas'},
  {value:'Gestão de saúde e de operadoras de saúde',label:'Gestão de saúde e de operadoras de saúde'},
  {value:'Gestão de Times',label:'Gestão de Times'},
  {value:'Gestão e Estratégia comercial',label:'Gestão e Estratégia comercial'},
  {value:'Governança; Tecnologia',label:'Governança; Tecnologia'},
  {value:'Growth Hacking',label:'Growth Hacking'},
  {value:'Hipnoterapia',label:'Hipnoterapia'},
  {value:'Imagens',label:'Imagens'},
  {value:'Indústria de Alimentos',label:'Indústria de Alimentos'},
  {value:'Industria de Medicamentos/ Qualidade',label:'Industria de Medicamentos/ Qualidade'},
  {value:'Indústria farmacêutica',label:'Indústria farmacêutica'},
  {value:'Indústria Financeira',label:'Indústria Financeira'},
  {value:'Informatica',label:'Informatica'},
  {value:'Infraestrutura Cloud',label:'Infraestrutura Cloud'},
  {value:'Inovacao',label:'Inovacao'},
  {value:'Inovação',label:'Inovação'},
  {value:'Instituições de Arte',label:'Instituições de Arte'},
  {value:'Inteligência de Mercado',label:'Inteligência de Mercado'},
  {value:'Investigação e Compliance',label:'Investigação e Compliance'},
  {value:'Investimento imobiliário',label:'Investimento imobiliário'},
  {value:'Investimentos',label:'Investimentos'},
  {value:'Investimentos ',label:'Investimentos '},
  {value:'Letras',label:'Letras'},
  {value:'Liderança e Gestão de Clientes',label:'Liderança e Gestão de Clientes'},
  {value:'Listagem de Àreas',label:'Listagem de Àreas'},
  {value:'Literatura',label:'Literatura'},
  {value:'Logistica',label:'Logistica'},
  {value:'Logística',label:'Logística'},
  {value:'Logística e Administração',label:'Logística e Administração'},
  {value:'Logística e Operações de Vendas',label:'Logística e Operações de Vendas'},
  {value:'Logistica e tecnologia',label:'Logistica e tecnologia'},
  {value:'Manutenção',label:'Manutenção'},
  {value:'Manutenção e Melhoria Contínua',label:'Manutenção e Melhoria Contínua'},
  {value:'Marketing',label:'Marketing'},
  {value:'Marketing - Bens de Consumo',label:'Marketing - Bens de Consumo'},
  {value:'Marketing (Gestão e Desenvolvimento de Produtos) e Planejamento Estratégico',label:'Marketing (Gestão e Desenvolvimento de Produtos) e Planejamento Estratégico'},
  {value:'Marketing corporativo',label:'Marketing corporativo'},
  {value:'Marketing Digital',label:'Marketing Digital'},
  {value:'Marketing e vendas',label:'Marketing e vendas'},
  {value:'Medicina',label:'Medicina'},
  {value:'Medicina veterinária',label:'Medicina veterinária'},
  {value:'Meio Ambiente',label:'Meio Ambiente'},
  {value:'Meio Ambiente.',label:'Meio Ambiente.'},
  {value:'Mercado de Capitais',label:'Mercado de Capitais'},
  {value:'Mercado Farmacêutico',label:'Mercado Farmacêutico'},
  {value:'Mercado Financeiro',label:'Mercado Financeiro'},
  {value:'Mídias Sociais',label:'Mídias Sociais'},
  {value:'Novos negócios e Educação',label:'Novos negócios e Educação'},
  {value:'Operação de vendas',label:'Operação de vendas'},
  {value:'Operações',label:'Operações'},
  {value:'Organização sem fins lucrativos',label:'Organização sem fins lucrativos'},
  {value:'Ourivesaria artística',label:'Ourivesaria artística'},
  {value:'Parceria e negócios',label:'Parceria e negócios'},
  {value:'Parcerias',label:'Parcerias'},
  {value:'Parte Administrativa e Financeira',label:'Parte Administrativa e Financeira'},
  {value:'Pesquisa & Desenvolvimento',label:'Pesquisa & Desenvolvimento'},
  {value:'Pesquisa e Desenvolvimento',label:'Pesquisa e Desenvolvimento'},
  {value:'Pesquisa e Desenvolvimento de Produtos',label:'Pesquisa e Desenvolvimento de Produtos'},
  {value:'Pesquisa e Tecnologia de Informação',label:'Pesquisa e Tecnologia de Informação'},
  {value:'Planejamento',label:'Planejamento'},
  {value:'Planejamento Produção',label:'Planejamento Produção'},
  {value:'Políticas Públicas',label:'Políticas Públicas'},
  {value:'Precificação',label:'Precificação'},
  {value:'Previdência',label:'Previdência'},
  {value:'Processos',label:'Processos'},
  {value:'produção de produtos cosméticos',label:'produção de produtos cosméticos'},
  {value:'Produção e Administração',label:'Produção e Administração'},
  {value:'Produção industrial',label:'Produção industrial'},
  {value:'Produtos Digitais',label:'Produtos Digitais'},
  {value:'Produtos Digitais ',label:'Produtos Digitais '},
  {value:'Produtos digitais de Educação',label:'Produtos digitais de Educação'},
  {value:'Programação',label:'Programação'},
  {value:'Psicologia',label:'Psicologia'},
  {value:'Psicologia é parcial',label:'Psicologia é parcial'},
  {value:'Psicopedagogia',label:'Psicopedagogia'},
  {value:'Publicidade Online',label:'Publicidade Online'},
  {value:'Qualidade de Fornecedores e Melhoria Contínua',label:'Qualidade de Fornecedores e Melhoria Contínua'},
  {value:'Qualidade e treinamentos',label:'Qualidade e treinamentos'},
  {value:'Recursos Humanos',label:'Recursos Humanos'},
  {value:'Redação e Produção Textual',label:'Redação e Produção Textual'},
  {value:'Redes de Computadores',label:'Redes de Computadores'},
  {value:'Reikiano',label:'Reikiano'},
  {value:'Revenue Management e Pricing',label:'Revenue Management e Pricing'},
  {value:'Risco Operacional / Acompanhamento de Projetos',label:'Risco Operacional / Acompanhamento de Projetos'},
  {value:'Risk Strategy Management',label:'Risk Strategy Management'},
  {value:'Saúde',label:'Saúde'},
  {value:'Saúde e Segurança do Trabalho',label:'Saúde e Segurança do Trabalho'},
  {value:'Segurança',label:'Segurança'},
  {value:'Segurança da Informação',label:'Segurança da Informação'},
  {value:'Segurança Digital',label:'Segurança Digital'},
  {value:'Segurança e Meio-Ambiente',label:'Segurança e Meio-Ambiente'},
  {value:'Seguros',label:'Seguros'},
  {value:'Serviço de Atendimento ao Cliente',label:'Serviço de Atendimento ao Cliente'},
  {value:'Serviços',label:'Serviços'},
  {value:'Sistema de Gestão Integrado Saude',label:'Sistema de Gestão Integrado Saude'},
  {value:'Sou estudante',label:'Sou estudante'},
  {value:'Startups',label:'Startups'},
  {value:'Sucesso do Cliente (Marketing)',label:'Sucesso do Cliente (Marketing)'},
  {value:'Suporte de TI',label:'Suporte de TI'},
  {value:'Suporte e Operações de TI',label:'Suporte e Operações de TI'},
  {value:'Supply Chain',label:'Supply Chain'},
  {value:'Supply Chain - Logística',label:'Supply Chain - Logística'},
  {value:'Suprimentos',label:'Suprimentos'},
  {value:'SUSTENTABILIDADE',label:'SUSTENTABILIDADE'},
  {value:'Technologia de software',label:'Technologia de software'},
  {value:'Tecnologia',label:'Tecnologia'},
  {value:'Tecnologia / Software',label:'Tecnologia / Software'},
  {value:'Tecnologia da informação',label:'Tecnologia da informação'},
  {value:'Tecnologia de informação',label:'Tecnologia de informação'},
  {value:'Tecnologia digital',label:'Tecnologia digital'},
  {value:'Tecnologia e Ecommerce',label:'Tecnologia e Ecommerce'},
  {value:'Tecnologia e Esportes',label:'Tecnologia e Esportes'},
  {value:'Tecnologia e meio ambiente.',label:'Tecnologia e meio ambiente.'},
  {value:'Tecnologia; Governança;',label:'Tecnologia; Governança;'},
  {value:'Telecom e Projetos de IoT',label:'Telecom e Projetos de IoT'},
  {value:'Tendências',label:'Tendências'},
  {value:'TI',label:'TI'},
  {value:'Time comercial',label:'Time comercial'},
  {value:'Trade Marketing (Construção da Estratégia de Vendas)',label:'Trade Marketing (Construção da Estratégia de Vendas)'},
  {value:'Trade Marketing/ Comercial',label:'Trade Marketing/ Comercial'},
  {value:'Transformação digital',label:'Transformação digital'},
  {value:'Trasnformação Digital',label:'Trasnformação Digital'},
  {value:'Turismo / Vendas / Gestão',label:'Turismo / Vendas / Gestão'},
  {value:'Varejo',label:'Varejo'},
  {value:'Varejo automotivo',label:'Varejo automotivo'},
  {value:'Varejo online',label:'Varejo online'},
  {value:'Vendas',label:'Vendas'},
  {value:'Vendas - Comercial',label:'Vendas - Comercial'},
  {value:'Vendas / Tecnologia da informação',label:'Vendas / Tecnologia da informação'},
  {value:'Vendas de Brinquedos e Licenciamento de Produtos',label:'Vendas de Brinquedos e Licenciamento de Produtos'},
  {value:'Vendas de equipamentos',label:'Vendas de equipamentos'},
  {value:'Vendas de Tecnologia',label:'Vendas de Tecnologia'},
  {value:'Vendas de Tecnologia (IT)',label:'Vendas de Tecnologia (IT)'},
  {value:'Vendas e Financas',label:'Vendas e Financas'},
  {value:'Vendas e Gerenciamento de Operacoes Terceirizadas',label:'Vendas e Gerenciamento de Operacoes Terceirizadas'},
  {value:'Vendas e Marketing',label:'Vendas e Marketing'},
  {value:'Vendas e Relacionamento com Clientes',label:'Vendas e Relacionamento com Clientes'},
  {value:'Vendas e Trade Marketing',label:'Vendas e Trade Marketing'},
  {value:'Vendas em tecnologia',label:'Vendas em tecnologia'},
  {value:'Vendas em TI',label:'Vendas em TI'},
  {value:'Venture Debt',label:'Venture Debt'},
  {value:'Veterinária',label:'Veterinária'},
  ]

  export default AreasList;