const CoursesList = [
  {curso: 'Administração'},
  {curso: 'Administração Pública'},
  {curso: 'Aeronautica'},
  {curso: 'Agrimensura'},
  {curso: 'Agroecologia'},
  {curso: 'Agronegócios e Agropecuária'},
  {curso: 'Agronomia'},
  {curso: 'Alimentos'},
  {curso: 'Análise e Desenvolvimento de Sistemas'},
  {curso: 'Animação'},
  {curso: 'Aquicultura'},
  {curso: 'Arqueologia'},
  {curso: 'Arquitetura e Urbanismo'},
  {curso: 'Arquivologia'},
  {curso: 'Artes'},
  {curso: 'Artes Cênicas'},
  {curso: 'Artes Plásticas'},
  {curso: 'Artes Visuais'},
  {curso: 'Astronomia'},
  {curso: 'Automação Industrial'},
  {curso: 'Banco de Dados'},
  {curso: 'Biblioteconomia'},
  {curso: 'Biocombustíveis'},
  {curso: 'Biologia'},
  {curso: 'Biomedicina'},
  {curso: 'Bioquímica'},
  {curso: 'Biossistemas'},
  {curso: 'Biotecnologia'},
  {curso: 'Biotecnologia e Bioquímica'},
  {curso: 'Ciência da Computação'},
  {curso: 'Ciência da Terra'},
  {curso: 'Ciências do Esporte'},
  {curso: 'Ciência de Dados'},
  {curso: 'Ciência e Economia'},
  {curso: 'Ciência e Tecnologia'},
  {curso: 'Ciência e Tecnologia das Águas'},
  {curso: 'Ciência e Tecnologia do Mar'},
  {curso: 'Ciência e Tecnologia de Alimentos'},
  {curso: 'Ciências Aeronáuticas'},
  {curso: 'Ciências Agrárias'},
  {curso: 'Ciências Atuariais'},
  {curso: 'Ciências Biológicas'},
  {curso: 'Ciências Biomédicas'},
  {curso: 'Ciências Contábeis'},
  {curso: 'Ciências da Natureza e suas Tecnologias'},
  {curso: 'Ciências dos Alimentos'},
  {curso: 'Ciências do Consumo'},
  {curso: 'Ciências e Humanidades'},
  {curso: 'Ciências Econômicas'},
  {curso: 'Ciências Fundamentais para a Saúde'},
  {curso: 'Ciências Humanas'},
  {curso: 'Ciências Matemáticas e da Terra'},
  {curso: 'Ciências Naturais e Exatas'},
  {curso: 'Ciências Rurais'},
  {curso: 'Ciências Sociais'},
  {curso: 'Cinema e Audiovisual'},
  {curso: 'Comércio Exterior'},
  {curso: 'Computação'},
  {curso: 'Comunicação Assistiva'},
  {curso: 'Comunicação das Artes do Corpo'},
  {curso: 'Comunicação Empresarial'},
  {curso: 'Comunicação e Informação'},
  {curso: 'Comunicação em Mídias Digitais'},
  {curso: 'Comunicação Institucional'},
  {curso: 'Comunicação Organizacional'},
  {curso: 'Comunicação Social'},
  {curso: 'Conservação e Restauro'},
  {curso: 'Construção Civil'},
  {curso: 'Construção de Edifícios'},
  {curso: 'Construção de Instrumentos Musicais'},
  {curso: 'Construção Naval'},
  {curso: 'Cooperativismo'},
  {curso: 'Cultura, Linguagens e Tecnologias Aplicadas'},
  {curso: 'Dança'},
  {curso: 'Defesa e Gestão Estratégica Internacional'},
  {curso: 'Desenho Industrial'},
  {curso: 'Design'},
  {curso: 'Design de Games'},
  {curso: 'Design de Interiores'},
  {curso: 'Design de Moda'},
  {curso: 'Design de Produto'},
  {curso: 'Design e Produção Gráfica'},
  {curso: 'Design Gráfico'},
  {curso: 'Direito'},
  {curso: 'Ecologia'},
  {curso: 'Economia'},
  {curso: 'Economia Doméstica'},
  {curso: 'Editoração'},
  {curso: 'Educação Física'},
  {curso: 'Educomunicação'},
  {curso: 'Eletrônica Industrial'},
  {curso: 'Eletrotécnica Industrial'},
  {curso: 'Energia e Sustentabilidade'},
  {curso: 'Energias Renováveis'},
  {curso: 'Enfermagem'},
  {curso: 'Engenharia Acústica'},
  {curso: 'Engenharia Aeronáutica'},
  {curso: 'Engenharia Agrícola'},
  {curso: 'Engenharia Agronômica'},
  {curso: 'Engenharia Ambiental e Sanitária'},
  {curso: 'Engenharia Biomédica'},
  {curso: 'Engenharia Bioquímica, de Bioprocessos e Biotecnologia'},
  {curso: 'Engenharia Cartográfica e de Agrimensura'},
  {curso: 'Engenharia Civil'},
  {curso: 'Engenharia da Computação'},
  {curso: 'Engenharia de Alimentos'},
  {curso: 'Engenharia de Biossistemas'},
  {curso: 'Engenharia de Controle e Automação'},
  {curso: 'Engenharia de Energia'},
  {curso: 'Engenharia de Inovação'},
  {curso: 'Engenharia de Materiais'},
  {curso: 'Engenharia de Minas'},
  {curso: 'Engenharia de Pesca'},
  {curso: 'Engenharia de Petróleo'},
  {curso: 'Engenharia de Produção'},
  {curso: 'Engenharia de Segurança no Trabalho'},
  {curso: 'Engenharia de Sistemas'},
  {curso: 'Engenharia de Software'},
  {curso: 'Engenharia de Telecomunicações'},
  {curso: 'Engenharia de Transporte e da Mobilidade'},
  {curso: 'Engenharia Elétrica'},
  {curso: 'Engenharia Eletrônica'},
  {curso: 'Engenharia Física'},
  {curso: 'Engenharia Florestal'},
  {curso: 'Engenharia Hídrica'},
  {curso: 'Engenharia Industrial Madeireira'},
  {curso: 'Engenharia Matemática'},
  {curso: 'Engenharia Mecânica'},
  {curso: 'Engenharia Mecatrônica'},
  {curso: 'Engenharia Metalúrgica'},
  {curso: 'Engenharia Naval'},
  {curso: 'Engenharia Nuclear'},
  {curso: 'Engenharia Química'},
  {curso: 'Engenharia Têxtil'},
  {curso: 'Escrita Criativa'},
  {curso: 'Esporte'},
  {curso: 'Estatística'},
  {curso: 'Estética e Cosmética'},
  {curso: 'Estudos de Gênero e Diversidade'},
  {curso: 'Estudos de Mídia'},
  {curso: 'Estudos Literários'},
  {curso: 'Eventos'},
  {curso: 'Fabricação Mecânica'},
  {curso: 'Farmácia'},
  {curso: 'Filosofia'},
  {curso: 'Física'},
  {curso: 'Física Biológica'},
  {curso: 'Física Médica'},
  {curso: 'Fisioterapia'},
  {curso: 'Fonoaudiologia'},
  {curso: 'Fotografia'},
  {curso: 'Gastronomia'},
  {curso: 'Geofísica'},
  {curso: 'Geografia'},
  {curso: 'Geologia'},
  {curso: 'Geoprocessamento'},
  {curso: 'Gerontologia'},
  {curso: 'Gestão Ambiental'},
  {curso: 'Gestão Comercial'},
  {curso: 'Gestão da Informação'},
  {curso: 'Gestão da Produção Industrial'},
  {curso: 'Gestão da Qualidade'},
  {curso: 'Gestão da Tecnologia da Informação'},
  {curso: 'Gestão de Cooperativas'},
  {curso: 'Gestão de Políticas Públicas'},
  {curso: 'Gestão de Recursos Humanos'},
  {curso: 'Gestão de Segurança Privada'},
  {curso: 'Gestão de Seguros'},
  {curso: 'Gestão de Turismo'},
  {curso: 'Gestão Desportiva e de Lazer'},
  {curso: 'Gestão Financeira'},
  {curso: 'Gestão Hospitalar'},
  {curso: 'Gestão Pública'},
  {curso: 'História'},
  {curso: 'História da Arte'},
  {curso: 'Hotelaria'},
  {curso: 'Humanidades'},
  {curso: 'Informática Biomédica'},
  {curso: 'Irrigação e Drenagem'},
  {curso: 'Jogos Digitais'},
  {curso: 'Jornalismo'},
  {curso: 'Lazer e Turismo'},
  {curso: 'Letras'},
  {curso: 'Linguística'},
  {curso: 'Logística'},
  {curso: 'Luteria'},
  {curso: 'Manutenção de Aeronaves'},
  {curso: 'Manutenção Industrial'},
  {curso: 'Marketing'},
  {curso: 'Gestão Pública para o Desenvolvimento Econômico e Social'},
  {curso: 'Matemática'},
  {curso: 'Matemática Aplicada'},
  {curso: 'Matemática Aplicada e Computacional'},
  {curso: 'Matemática e Computação e suas Tecnologias'},
  {curso: 'Materiais'},
  {curso: 'Materiais, Processos e Componentes Eletrônicos'},
  {curso: 'Mecânica'},
  {curso: 'Mecatrônica Industrial'},
  {curso: 'Medicina'},
  {curso: 'Medicina Veterinária'},
  {curso: 'Meteorologia'},
  {curso: 'Mineração, Petróleo e Gás'},
  {curso: 'Moda'},
  {curso: 'Multimídia'},
  {curso: 'Museologia'},
  {curso: 'Música'},
  {curso: 'Musicoterapia'},
  {curso: 'Nanotecnologia'},
  {curso: 'Naturologia'},
  {curso: 'Negócios Imobiliários'},
  {curso: 'Neurociências'},
  {curso: 'Nutrição'},
  {curso: 'Obstetrícia'},
  {curso: 'Oceanografia'},
  {curso: 'Odontologia'},
  {curso: 'Oftálmica'},
  {curso: 'Optometria'},
  {curso: 'Papel e Celulose'},
  {curso: 'Pedagogia'},
  {curso: 'Petróleo e Gás'},
  {curso: 'Pilotagem Profissional de Aeronaves'},
  {curso: 'Processos Gerenciais'},
  {curso: 'Processos Metalúrgicos'},
  {curso: 'Processos Químicos'},
  {curso: 'Produção Audiovisual'},
  {curso: 'Produção Cênica'},
  {curso: 'Produção Cultural'},
  {curso: 'Produção de Bebidas'},
  {curso: 'Produção Editorial'},
  {curso: 'Produção Fonográfica'},
  {curso: 'Produção Moveleira'},
  {curso: 'Produção Multimídia'},
  {curso: 'Produção de Música Eletrônica'},
  {curso: 'Produção Publicitária'},
  {curso: 'Produção Sucroalcooleira'},
  {curso: 'Produção Têxtil'},
  {curso: 'Psicologia'},
  {curso: 'Programação Cultural'},
  {curso: 'Psicopedagogia'},
  {curso: 'Publicidade e Propaganda'},
  {curso: 'Química'},
  {curso: 'Quiropraxia'},
  {curso: 'Química Industrial'},
  {curso: 'Rádio, TV e Internet'},
  {curso: 'Radiologia'},
  {curso: 'Relações Internacionais'},
  {curso: 'Relações Públicas'},
  {curso: 'Rochas Ornamentais'},
  {curso: 'Saneamento Ambiental'},
  {curso: 'Saúde'},
  {curso: 'Saúde Coletiva'},
  {curso: 'Saúde Pública'},
  {curso: 'Secretariado'},
  {curso: 'Secretariado Executivo'},
  {curso: 'Segurança da Informação'},
  {curso: 'Segurança'},
  {curso: 'Segurança no Trabalho'},
  {curso: 'Segurança Pública'},
  {curso: 'Serviço Social'},
  {curso: 'Serviços Judiciários e Notariais'},
  {curso: 'Silvicultura'},
  {curso: 'Sistemas Biomédicos'},
  {curso: 'Sistemas de Informação'},
  {curso: 'Sistemas de Telecomunicações'},
  {curso: 'Sistemas Elétricos'},
  {curso: 'Sistemas Embarcados'},
  {curso: 'Sistemas para Internet'},
  {curso: 'Teatro'},
  {curso: 'Tecnologia da Informação'},
  {curso: 'Tecnologia da Madeira'},
  {curso: 'Tecnologia de Laticínios'},
  {curso: 'Telecomunicações'},
  {curso: 'Teologia'},
  {curso: 'Terapia Ocupacional'},
  {curso: 'Têxtil e Moda'},
  {curso: 'Tradutor e Intérprete'},
  {curso: 'Transporte'},
  {curso: 'Turismo'},
  {curso: 'Zootecnia'},
]
  
  export default CoursesList;