import React from 'react'
import Image from 'next/image'

import {Heading} from '../Heading'

import plataformaLogo from '../../assets/image/logo-semear.png'

const courses = [
  {curso: 'Administração'},
  {curso: 'Administração Pública'},
  {curso: 'Aeronautica'},
  {curso: 'Agrimensura'},
  {curso: 'Agroecologia'},
  {curso: 'Agronegócios e Agropecuária'},
  {curso: 'Agronomia'},
  {curso: 'Alimentos'},
  {curso: 'Análise e Desenvolvimento de Sistemas'},
  {curso: 'Animação'},
  {curso: 'Aquicultura'},
  {curso: 'Arqueologia'},
  {curso: 'Arquitetura e Urbanismo'},
  {curso: 'Arquivologia'},
  {curso: 'Artes'},
  {curso: 'Artes Cênicas'},
  {curso: 'Artes Plásticas'},
  {curso: 'Artes Visuais'},
  {curso: 'Astronomia'},
  {curso: 'Automação Industrial'},
  {curso: 'Banco de Dados'},
  {curso: 'Biblioteconomia'},
  {curso: 'Biocombustíveis'},
  {curso: 'Biologia'},
  {curso: 'Biomedicina'},
  {curso: 'Bioquímica'},
  {curso: 'Biossistemas'},
  {curso: 'Biotecnologia'},
  {curso: 'Biotecnologia e Bioquímica'},
  {curso: 'Ciência da Computação'},
  {curso: 'Ciência da Terra'},
  {curso: 'Ciências do Esporte'},
  {curso: 'Ciência de Dados'},
  {curso: 'Ciência e Economia'},
  {curso: 'Ciência e Tecnologia'},
  {curso: 'Ciência e Tecnologia das Águas'},
  {curso: 'Ciência e Tecnologia do Mar'},
  {curso: 'Ciência e Tecnologia de Alimentos'},
  {curso: 'Ciências Aeronáuticas'},
  {curso: 'Ciências Agrárias'},
  {curso: 'Ciências Atuariais'},
  {curso: 'Ciências Biológicas'},
  {curso: 'Ciências Biomédicas'},
  {curso: 'Ciências Contábeis'},
  {curso: 'Ciências da Natureza e suas Tecnologias'},
  {curso: 'Ciências dos Alimentos'},
  {curso: 'Ciências do Consumo'},
  {curso: 'Ciências e Humanidades'},
  {curso: 'Ciências Econômicas'},
  {curso: 'Ciências Fundamentais para a Saúde'},
  {curso: 'Ciências Humanas'},
  {curso: 'Ciências Matemáticas e da Terra'},
  {curso: 'Ciências Naturais e Exatas'},
  {curso: 'Ciências Rurais'},
  {curso: 'Ciências Sociais'},
  {curso: 'Cinema e Audiovisual'},
  {curso: 'Comércio Exterior'},
  {curso: 'Computação'},
  {curso: 'Comunicação Assistiva'},
  {curso: 'Comunicação das Artes do Corpo'},
  {curso: 'Comunicação Empresarial'},
  {curso: 'Comunicação e Informação'},
  {curso: 'Comunicação em Mídias Digitais'},
  {curso: 'Comunicação Institucional'},
  {curso: 'Comunicação Organizacional'},
  {curso: 'Comunicação Social'},
  {curso: 'Conservação e Restauro'},
  {curso: 'Construção Civil'},
  {curso: 'Construção de Edifícios'},
  {curso: 'Construção de Instrumentos Musicais'},
  {curso: 'Construção Naval'},
  {curso: 'Cooperativismo'},
  {curso: 'Cultura, Linguagens e Tecnologias Aplicadas'},
  {curso: 'Dança'},
  {curso: 'Defesa e Gestão Estratégica Internacional'},
  {curso: 'Desenho Industrial'},
  {curso: 'Design'},
  {curso: 'Design de Games'},
  {curso: 'Design de Interiores'},
  {curso: 'Design de Moda'},
  {curso: 'Design de Produto'},
  {curso: 'Design e Produção Gráfica'},
  {curso: 'Design Gráfico'},
  {curso: 'Direito'},
  {curso: 'Ecologia'},
  {curso: 'Economia'},
  {curso: 'Economia Doméstica'},
  {curso: 'Editoração'},
  {curso: 'Educação Física'},
  {curso: 'Educomunicação'},
  {curso: 'Eletrônica Industrial'},
  {curso: 'Eletrotécnica Industrial'},
  {curso: 'Energia e Sustentabilidade'},
  {curso: 'Energias Renováveis'},
  {curso: 'Enfermagem'},
  {curso: 'Engenharia Acústica'},
  {curso: 'Engenharia Aeronáutica'},
  {curso: 'Engenharia Agrícola'},
  {curso: 'Engenharia Agronômica'},
  {curso: 'Engenharia Ambiental e Sanitária'},
  {curso: 'Engenharia Biomédica'},
  {curso: 'Engenharia Bioquímica, de Bioprocessos e Biotecnologia'},
  {curso: 'Engenharia Cartográfica e de Agrimensura'},
  {curso: 'Engenharia Civil'},
  {curso: 'Engenharia da Computação'},
  {curso: 'Engenharia de Alimentos'},
  {curso: 'Engenharia de Biossistemas'},
  {curso: 'Engenharia de Controle e Automação'},
  {curso: 'Engenharia de Energia'},
  {curso: 'Engenharia de Inovação'},
  {curso: 'Engenharia de Materiais'},
  {curso: 'Engenharia de Minas'},
  {curso: 'Engenharia de Pesca'},
  {curso: 'Engenharia de Petróleo'},
  {curso: 'Engenharia de Produção'},
  {curso: 'Engenharia de Segurança no Trabalho'},
  {curso: 'Engenharia de Sistemas'},
  {curso: 'Engenharia de Software'},
  {curso: 'Engenharia de Telecomunicações'},
  {curso: 'Engenharia de Transporte e da Mobilidade'},
  {curso: 'Engenharia Elétrica'},
  {curso: 'Engenharia Eletrônica'},
  {curso: 'Engenharia Física'},
  {curso: 'Engenharia Florestal'},
  {curso: 'Engenharia Hídrica'},
  {curso: 'Engenharia Industrial Madeireira'},
  {curso: 'Engenharia Matemática'},
  {curso: 'Engenharia Mecânica'},
  {curso: 'Engenharia Mecatrônica'},
  {curso: 'Engenharia Metalúrgica'},
  {curso: 'Engenharia Naval'},
  {curso: 'Engenharia Nuclear'},
  {curso: 'Engenharia Química'},
  {curso: 'Engenharia Têxtil'},
  {curso: 'Escrita Criativa'},
  {curso: 'Esporte'},
  {curso: 'Estatística'},
  {curso: 'Estética e Cosmética'},
  {curso: 'Estudos de Gênero e Diversidade'},
  {curso: 'Estudos de Mídia'},
  {curso: 'Estudos Literários'},
  {curso: 'Eventos'},
  {curso: 'Fabricação Mecânica'},
  {curso: 'Farmácia'},
  {curso: 'Filosofia'},
  {curso: 'Física'},
  {curso: 'Física Biológica'},
  {curso: 'Física Médica'},
  {curso: 'Fisioterapia'},
  {curso: 'Fonoaudiologia'},
  {curso: 'Fotografia'},
  {curso: 'Gastronomia'},
  {curso: 'Geofísica'},
  {curso: 'Geografia'},
  {curso: 'Geologia'},
  {curso: 'Geoprocessamento'},
  {curso: 'Gerontologia'},
  {curso: 'Gestão Ambiental'},
  {curso: 'Gestão Comercial'},
  {curso: 'Gestão da Informação'},
  {curso: 'Gestão da Produção Industrial'},
  {curso: 'Gestão da Qualidade'},
  {curso: 'Gestão da Tecnologia da Informação'},
  {curso: 'Gestão de Cooperativas'},
  {curso: 'Gestão de Políticas Públicas'},
  {curso: 'Gestão de Recursos Humanos'},
  {curso: 'Gestão de Segurança Privada'},
  {curso: 'Gestão de Seguros'},
  {curso: 'Gestão de Turismo'},
  {curso: 'Gestão Desportiva e de Lazer'},
  {curso: 'Gestão Financeira'},
  {curso: 'Gestão Hospitalar'},
  {curso: 'Gestão Pública'},
  {curso: 'História'},
  {curso: 'História da Arte'},
  {curso: 'Hotelaria'},
  {curso: 'Humanidades'},
  {curso: 'Informática Biomédica'},
  {curso: 'Irrigação e Drenagem'},
  {curso: 'Jogos Digitais'},
  {curso: 'Jornalismo'},
  {curso: 'Lazer e Turismo'},
  {curso: 'Letras'},
  {curso: 'Linguística'},
  {curso: 'Logística'},
  {curso: 'Luteria'},
  {curso: 'Manutenção de Aeronaves'},
  {curso: 'Manutenção Industrial'},
  {curso: 'Marketing'},
  {curso: 'Gestão Pública para o Desenvolvimento Econômico e Social'},
  {curso: 'Matemática'},
  {curso: 'Matemática Aplicada'},
  {curso: 'Matemática Aplicada e Computacional'},
  {curso: 'Matemática e Computação e suas Tecnologias'},
  {curso: 'Materiais'},
  {curso: 'Materiais, Processos e Componentes Eletrônicos'},
  {curso: 'Mecânica'},
  {curso: 'Mecatrônica Industrial'},
  {curso: 'Medicina'},
  {curso: 'Medicina Veterinária'},
  {curso: 'Meteorologia'},
  {curso: 'Mineração, Petróleo e Gás'},
  {curso: 'Moda'},
  {curso: 'Multimídia'},
  {curso: 'Museologia'},
  {curso: 'Música'},
  {curso: 'Musicoterapia'},
  {curso: 'Nanotecnologia'},
  {curso: 'Naturologia'},
  {curso: 'Negócios Imobiliários'},
  {curso: 'Neurociências'},
  {curso: 'Nutrição'},
  {curso: 'Obstetrícia'},
  {curso: 'Oceanografia'},
  {curso: 'Odontologia'},
  {curso: 'Oftálmica'},
  {curso: 'Optometria'},
  {curso: 'Papel e Celulose'},
  {curso: 'Pedagogia'},
  {curso: 'Petróleo e Gás'},
  {curso: 'Pilotagem Profissional de Aeronaves'},
  {curso: 'Processos Gerenciais'},
  {curso: 'Processos Metalúrgicos'},
  {curso: 'Processos Químicos'},
  {curso: 'Produção Audiovisual'},
  {curso: 'Produção Cênica'},
  {curso: 'Produção Cultural'},
  {curso: 'Produção de Bebidas'},
  {curso: 'Produção Editorial'},
  {curso: 'Produção Fonográfica'},
  {curso: 'Produção Moveleira'},
  {curso: 'Produção Multimídia'},
  {curso: 'Produção de Música Eletrônica'},
  {curso: 'Produção Publicitária'},
  {curso: 'Produção Sucroalcooleira'},
  {curso: 'Produção Têxtil'},
  {curso: 'Psicologia'},
  {curso: 'Programação Cultural'},
  {curso: 'Psicopedagogia'},
  {curso: 'Publicidade e Propaganda'},
  {curso: 'Química'},
  {curso: 'Quiropraxia'},
  {curso: 'Química Industrial'},
  {curso: 'Rádio, TV e Internet'},
  {curso: 'Radiologia'},
  {curso: 'Relações Internacionais'},
  {curso: 'Relações Públicas'},
  {curso: 'Rochas Ornamentais'},
  {curso: 'Saneamento Ambiental'},
  {curso: 'Saúde'},
  {curso: 'Saúde Coletiva'},
  {curso: 'Saúde Pública'},
  {curso: 'Secretariado'},
  {curso: 'Secretariado Executivo'},
  {curso: 'Segurança da Informação'},
  {curso: 'Segurança'},
  {curso: 'Segurança no Trabalho'},
  {curso: 'Segurança Pública'},
  {curso: 'Serviço Social'},
  {curso: 'Serviços Judiciários e Notariais'},
  {curso: 'Silvicultura'},
  {curso: 'Sistemas Biomédicos'},
  {curso: 'Sistemas de Informação'},
  {curso: 'Sistemas de Telecomunicações'},
  {curso: 'Sistemas Elétricos'},
  {curso: 'Sistemas Embarcados'},
  {curso: 'Sistemas para Internet'},
  {curso: 'Teatro'},
  {curso: 'Tecnologia da Informação'},
  {curso: 'Tecnologia da Madeira'},
  {curso: 'Tecnologia de Laticínios'},
  {curso: 'Telecomunicações'},
  {curso: 'Teologia'},
  {curso: 'Terapia Ocupacional'},
  {curso: 'Têxtil e Moda'},
  {curso: 'Tradutor e Intérprete'},
  {curso: 'Transporte'},
  {curso: 'Turismo'},
  {curso: 'Zootecnia'},
]

const area = [
  {area: 'Não encontrei minha área'},
  {area: 'Academica e Pesquisa'},
  {area: 'Administração de Empresas'},
  {area: 'Administração e Governança'},
  {area: 'Administração e Vendas'},
  {area: 'Advocacia'},
  {area: 'Agricultura'},
  {area: 'Agronegócios'},
  {area: 'Alimentos'},
  {area: 'Análise de Dados'},
  {area: 'Análise de Dados e Experiência do Cliente'},
  {area: 'Analise de Risco'},
  {area: 'Análise Financeira'},
  {area: 'Análise Química'},
  {area: 'Área Comercial'},
  {area: 'Área Comercial em Seguros'},
  {area: 'Área Comercial Vendas'},
  {area: 'Área Social'},
  {area: 'Arquitetura'},
  {area: 'Arquitetura de Sistemas'},
  {area: 'Arte Terapia'},
  {area: 'Artes'},
  {area: 'Atendimento ao Cliente'},
  {area: 'Auditoria'},
  {area: 'Auditoria e Contabilidade'},
  {area: 'Auditoria Interna'},
  {area: 'Auditoria Financeira'},
  {area: 'Bancos'},
  {area: 'Biologia'},
  {area: 'Biomedicina'},
  {area: 'Branding'},
  {area: 'Cadeia de Suprimentos'},
  {area: 'Carreira Militar'},
  {area: 'Ciências Sociais Aplicadas: Design'},
  {area: 'Cloud Computing'},
  {area: 'Coach de Carreira'},
  {area: 'Coaching e Treinamentos'},
  {area: 'Comercial'},
  {area: 'Comercial/Marketing'},
  {area: 'Comércio'},
  {area: 'Compliance'},
  {area: 'Compras'},
  {area: 'Compras / Suprimentos'},
  {area: 'Compras/ Gestão'},
  {area: 'Comunicação'},
  {area: 'Consultoria'},
  {area: 'Consultoria em Gestão de Negócios e Mercado'},
  {area: 'Criatividade'},
  {area: 'CRM'},
  {area: 'Customer Experience'},
  {area: 'Customer Success'},
  {area: 'Data Analytics'},
  {area: 'Data Science'},
  {area: 'Desenvolvimento Comercial'},
  {area: 'Desenvolvimento Comunitário.'},
  {area: 'Desenvolvimento de Carreira'},
  {area: 'Desenvolvimento de Negócios'},
  {area: 'Desenvolvimento de Software'},
  {area: 'Desenvolvimento de Websites'},
  {area: 'Design de Serviços'},
  {area: 'Direito'},
  {area: 'E-commerce'},
  {area: 'Educaçao'},
  {area: 'Educação'},
  {area: 'Educação Ambiental'},
  {area: 'Educação e Arte'},
  {area: 'Educação e Desenvolvimento Pessoal'},
  {area: 'Educação e Gestão de Pessoas'},
  {area: 'Educação e Pesquisa'},
  {area: 'Educação Não-Formal'},
  {area: 'Educação'},
  {area: 'Capoeira'},
  {area: 'Eletrodomesticos'},
  {area: 'Empreendedorismo'},
  {area: 'Empreendedorismo Social'},
  {area: 'Energias Renováveis'},
  {area: 'Engenharia'},
  {area: 'Engenharia de Alimentos'},
  {area: 'Escrita'},
  {area: 'Estrategia'},
  {area: 'Estratégia de Produto - Indústria Farmacêutica'},
  {area: 'Ética e Integridade Científica'},
  {area: 'Eventos de negócios em saúde'},
  {area: 'Experiência do Cliente'},
  {area: 'Filosofia'},
  {area: 'Finanças'},
  {area: 'Física'},
  {area: 'Fotografia'},
  {area: 'Geografia'},
  {area: 'Gerenciamento'},
  {area: 'Gerenciamento de Produtos'},
  {area: 'Gestão Administrativa'},
  {area: 'Gestão Ágil'},
  {area: 'Gestão da Cadeia de Suprimentos'},
  {area: 'Gestão de Dados e Estratégia'},
  {area: 'Gestão de Negócios'},
  {area: 'Gestão de Pessoas'},
  {area: 'Gestão de Processos'},
  {area: 'Gestão de Produtos Digitais'},
  {area: 'Gestão de Produtos.'},
  {area: 'Gestão de Projetos'},
  {area: 'Gestão de Riscos e Prevenção de Perdas'},
  {area: 'Gestão de Saúde'},
  {area: 'Gestão de Times'},
  {area: 'Gestão e Estratégia comercial'},
  {area: 'Governança e Tecnologia'},
  {area: 'Growth Hacking'},
  {area: 'Hipnoterapia'},
  {area: 'Imagens'},
  {area: 'Indústria de Alimentos'},
  {area: 'Industria de Medicamentos/ Qualidade'},
  {area: 'Indústria Farmacêutica'},
  {area: 'Indústria Financeira'},
  {area: 'Informatica'},
  {area: 'Infraestrutura Cloud'},
  {area: 'Inovação'},
  {area: 'Instituições de Arte'},
  {area: 'Inteligência de Mercado'},
  {area: 'Investigação e Compliance'},
  {area: 'Investimento Imobiliário'},
  {area: 'Investimentos'},
  {area: 'Letras'},
  {area: 'Liderança e Gestão de Clientes'},
  {area: 'Literatura'},
  {area: 'Logística'},
  {area: 'Logística e Administração'},
  {area: 'Logística e Operações de Vendas'},
  {area: 'Logistica e Tecnologia'},
  {area: 'Manutenção'},
  {area: 'Manutenção e Melhoria Contínua'},
  {area: 'Marketing'},
  {area: 'Marketing - Bens de Consumo'},
  {area: 'Marketing Corporativo'},
  {area: 'Marketing Digital'},
  {area: 'Marketing e Vendas'},
  {area: 'Medicina'},
  {area: 'Medicina Veterinária'},
  {area: 'Meio Ambiente'},
  {area: 'Mercado de Capitais'},
  {area: 'Mercado Farmacêutico'},
  {area: 'Mercado Financeiro'},
  {area: 'Mídias Sociais'},
  {area: 'Novos Negócios e Educação'},
  {area: 'Operação de Vendas'},
  {area: 'Operações'},
  {area: 'Organização Sem Fins Lucrativos'},
  {area: 'Ourivesaria Artística'},
  {area: 'Parceria e Aegócios'},
  {area: 'Parcerias'},
  {area: 'Parte Administrativa e Financeira'},
  {area: 'Pesquisa & Desenvolvimento'},
  {area: 'Pesquisa e Desenvolvimento'},
  {area: 'Pesquisa e Desenvolvimento de Produtos'},
  {area: 'Pesquisa e Tecnologia de Informação'},
  {area: 'Planejamento'},
  {area: 'Planejamento Produção'},
  {area: 'Políticas Públicas'},
  {area: 'Precificação'},
  {area: 'Previdência'},
  {area: 'Processos'},
  {area: 'Produção de Cosméticos'},
  {area: 'Produção e Administração'},
  {area: 'Produção Industrial'},
  {area: 'Produtos Digitais'},
  {area: 'Produtos Digitais de Educação'},
  {area: 'Programação'},
  {area: 'Psicologia'},
  {area: 'Psicopedagogia'},
  {area: 'Publicidade Online'},
  {area: 'Qualidade de Fornecedores e Melhoria Contínua'},
  {area: 'Qualidade e Treinamentos'},
  {area: 'Recursos Humanos'},
  {area: 'Redação e Produção Textual'},
  {area: 'Redes de Computadores'},
  {area: 'Reikiano'},
  {area: 'Revenue Management e Pricing'},
  {area: 'Risco Operacional / Acompanhamento de Projetos'},
  {area: 'Risk Strategy Management'},
  {area: 'Saúde'},
  {area: 'Saúde e Segurança do Trabalho'},
  {area: 'Segurança'},
  {area: 'Segurança da Informação'},
  {area: 'Segurança Digital'},
  {area: 'Segurança e Meio-Ambiente'},
  {area: 'Seguros'},
  {area: 'Serviço de Atendimento ao Cliente'},
  {area: 'Serviços'},
  {area: 'Sistema de Gestão Integrado Saude'},
  {area: 'Startups'},
  {area: 'Sucesso do Cliente (Marketing)'},
  {area: 'Suporte de TI'},
  {area: 'Suporte e Operações de TI'},
  {area: 'Supply Chain'},
  {area: 'Suprimentos'},
  {area: 'Sustentabilidade'},
  {area: 'Technologia de software'},
  {area: 'Tecnologia'},
  {area: 'Tecnologia / Software'},
  {area: 'Tecnologia da Informação'},
  {area: 'Tecnologia Digital'},
  {area: 'Tecnologia e Ecommerce'},
  {area: 'Tecnologia e Esportes'},
  {area: 'Tecnologia e Meio ambiente.'},
  {area: 'Telecomunicação e Projetos de IoT'},
  {area: 'Tendências'},
  {area: 'Time comercial'},
  {area: 'Trade Marketing/ Comercial'},
  {area: 'Trasnformação Digital'},
  {area: 'Turismo'},
  {area: 'Vendas'},
  {area: 'Vendas - Comercial'},
  {area: 'Vendas de Brinquedos e Licenciamento de Produtos'},
  {area: 'Vendas de Equipamentos'},
  {area: 'Vendas de Tecnologia'},
  {area: 'Vendas e Finanças'},
  {area: 'Vendas e Gerenciamento de Operacoes Terceirizadas'},
  {area: 'Vendas e Marketing'},
  {area: 'Vendas e Relacionamento com Clientes'},
  {area: 'Vendas e Trade Marketing'},
  {area: 'Venture Debt'},
  {area: 'Veterinária'},
]

const StepInfos = (props) => {
  if (props.currentStep !== 1) {
    return null
  }

  return (
    <fieldset>
      <div className="plataforma-logo2">
        <Image src={plataformaLogo} />
      </div>
      <Heading
        level="h4"
        horizontalPosition="center"
        ftColor="quinary"
        className="fs-title"
      >
        Infos Profissionais 📋
      </Heading>
      <Heading
        level="h6"
        horizontalPosition="center"
        ftColor="quinary"
        className="fs-subtitle"
      >
        Passo 4
      </Heading>

      <input
        list="datalist0"
        name="school"
        placeholder="Qual seu nível de escolaridade"
        value={props.school}
        onChange={props.handleChange}
        required
      />
      <datalist id="datalist0">
        <option value="Fundamental - Incompleto" />
        <option value="Fundamental - Completo" />
        <option value="Médio - Incompleto" />
        <option value="Médio - Completo" />
        <option value="Superior - Cursando" />
        <option value="Superior - Completo" />
        <option value="Pós-graduação - Incompleto" />
        <option value="Pós-graduação - Completo" />
        <option value="Mestrado - Incompleto" />
        <option value="Mestrado - Completo" />
        <option value="Doutorado - Incompleto" />
        <option value="Doutorado - Completo" />
      </datalist>
      <input
        type="list"
        list="datalist4"
        name="courses"
        placeholder="Qual seu curso?"
        onChange={props.handleChange}
        required
      />
      <datalist id="datalist4">
        {courses.map((item, index) => (
          <option value={item.curso} key={index} />
        ))}
      </datalist>
      <input
        type="list"
        list="datalist5"
        name="areas"
        placeholder="Qual sua principal area de atuação?"
        onChange={props.handleChange}
        required
      />
      <datalist id="datalist5">
        {area.map((item, index) => (
          <option value={item.area} key={index} />
        ))}
      </datalist>
      <input
        type="list"
        list="datalist6"
        name="areas"
        placeholder="Tem alguma área secundária de atuação?"
        onChange={props.handleChange}
        required
      />
      <datalist id="datalist6">
        {area.map((item, index) => (
          <option value={item.area} key={index} />
        ))}
      </datalist>

      <input
        type="url"
        name="site"
        placeholder="Você tem algum site pessoal ? (ex.: Linkedin ou Portfólio)"
        value={props.site}
        onChange={props.handleChange}
        required
      />
      
      <Heading level="h6">
        Gostaria de Adicionar uma Imagem ao seu perfil ?
      </Heading>
      <input type="file" accept="image/*" />

    </fieldset>
  )
}

export default StepInfos
